config/routes.rb
Rails.application.routes.draw do
  
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  root 'static_pages#test'
  
  get 'static_pages/home'

  get 'static_pages/help'
  
  get   '/home'  , to:'static_pages#home'
  get   '/music' , to:'static_pages#music'
  get   '/help'  , to:'static_pages#help'
  get   '/signup', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top navbar-inverse ">
      <div class="row">
      <div class="container-fluid">
        <div class="navbar-header">
       				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#rNavbar">
        					<span class="icon-bar"></span>
        					<span class="icon-bar"></span>
        					<span class="icon-bar"></span>
      				</button>
       				<a class="navbar-brand" href="#">Home Server</a>
      		</div>	
        <nav>
          <div class="collapse navbar-collapse" id="rNavbar" >  
          <ul class="nav navbar-nav">
        					<li class="active" ><a href="/home">Home</a></li>
        					<li><a href="/music">Music</a></li>
        					<li><a href="/help">HelpTest</a></li>
        					<% if logged_in? %>
                    <li><%= link_to "Users", users_path %></li>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                          Account <b class="caret"></b>
                      </a>
                      <ul class="dropdown-menu">
                        <li><%= link_to "Profile", current_user %></li>
                        <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                        <li class="divider"></li>
                        <li>
                          <%= link_to "Log out", logout_path, method: :delete %>
                        </li>
                      </ul>
                    </li>
                  <% else %>
                      <li><%= link_to "Log in", login_path %></li>
                  <% end %>
      		</ul>
          </div>
        </nav>
        </div>
        </div>
      </div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
      
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HomeServerApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

  </head>

  <body>
    <%= render 'layouts/header' %>
    
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
    
  </body>
</html>